import type { User, Complaint } from './definitions';

export const users: User[] = [
  { id: '1', name: 'Alice Johnson', email: 'alice@example.com', role: 'citizen' },
  { id: '2', name: 'Bob Williams', email: 'bob@example.com', role: 'citizen' },
  { id: '3', name: 'Charlie Brown', email: 'admin@example.com', role: 'admin' },
];

export const complaints: Complaint[] = [
  {
    id: 'cmp-001',
    title: 'Large pothole on Main St',
    category: 'Roads',
    description: 'A very large and dangerous pothole has formed in the westbound lane of Main Street, near the intersection with Oak Avenue. It has already caused damage to my car\'s tire.',
    location: 'Main St & Oak Ave',
    phone: '5551234567',
    email: 'alice@example.com',
    status: 'Pending',
    priority: 'High',
    date: '2024-05-15T09:30:00Z',
    userId: '1',
  },
  {
    id: 'cmp-002',
    title: 'Streetlight out in City Park',
    category: 'Parks',
    description: 'The main streetlight along the central path in City Park is not working. It makes the park feel unsafe after dark.',
    location: 'City Park, central path',
    phone: '5551234567',
    email: 'alice@example.com',
    status: 'In Progress',
    priority: 'Medium',
    date: '2024-05-18T14:00:00Z',
    userId: '1',
  },
  {
    id: 'cmp-003',
    title: 'Bus Route 5 is consistently late',
    category: 'Public Transport',
    description: 'The morning bus for Route 5 arrives at the downtown stop 10-15 minutes late almost every day this month, causing me to be late for work.',
    location: 'Downtown Bus Stop #123',
    phone: '5557654321',
    email: 'bob@example.com',
    status: 'Resolved',
    priority: 'Medium',
    date: '2024-05-10T08:45:00Z',
    userId: '2',
  },
  {
    id: 'cmp-004',
    title: 'Water pipe leak on 2nd Ave',
    category: 'Utilities',
    description: 'There is a constant stream of water coming from a crack in the sidewalk on 2nd Avenue. It has been going on for 3 days and is wasting a lot of water.',
    location: '123 2nd Avenue',
    phone: '5557654321',
    email: 'bob@example.com',
    status: 'Rejected',
    priority: 'High',
    date: '2024-05-20T11:20:00Z',
    userId: '2',
  },
];
